[package]
name = "navi"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
bluer = { version = "0.17.3", features = ["full"] }
futures = "0.3.31"
clap = { version = "4.5.38", features = ["derive"] }
